name: Build FujiNet-PC Launcher

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  workflow_dispatch:

jobs:
#   build-ubuntu-22:
#     runs-on: ubuntu-22.04
#     name: Ubuntu 22.04

#     steps:
#     - name: '🧰 Checkout Launcher'
#       uses: actions/checkout@v3
#       with:
#         path: fujinet-pc-launcher

#     - name: '🧰 Checkout Emulator Bridge'
#       uses: actions/checkout@v3
#       with:
#         repository: FujiNetWIFI/fujinet-emulator-bridge
#         path: fujinet-emulator-bridge

#     - name: 'List directories'
#       run: |
#         ls -la .
#         ls -la ..

  build-windows:
    runs-on: windows-latest
    name: Windows
    defaults:
      run:
        shell: bash

    steps:
    - name: '🧰 Checkout Launcher'
      uses: actions/checkout@v3
      with:
        path: fujinet-pc-launcher

    - name: '🧰 Checkout Emulator Bridge'
      uses: actions/checkout@v3
      with:
        repository: FujiNetWIFI/fujinet-emulator-bridge
        path: fujinet-emulator-bridge

    - name: 'Copy NetSIO hub module'
      run: cp -av fujinet-emulator-bridge/fujinet-bridge/netsiohub fujinet-pc-launcher
      
    - name: 'List directories'
      run: |
        pwd
        ls -la .
        ls -la fujinet-pc-launcher

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: List versions
      run: |
        python --version
        pip --version

    - name: Install requirements
      shell: cmd
      working-directory: fujinet-pc-launcher
      run: pip install -r requirements_build.txt

    - name: '🚧 Build FujiNet-PC Launcher'
      shell: cmd
      working-directory: fujinet-pc-launcher
      run: pyinstaller --clean --onedir --noconfirm --noconsole --python-option u --name launcher --icon launcher\images\launcher-bg.ico --add-data launcher\images;images  launcher\__main__.py

    - name: 'List dist'
      run: ls -la fujinet-pc-launcher/dist
      
